### ISSUE TITLE
ValueError: Unknown engine: pyarrow (valid options are "c", "python", or "python-fwf")

### ISSUE THREAD

**Issue by sherlie831** [ncos/pydvs#2]
Hi, I'm trying to run evimo-gen.py, but an error occurs at line 345:
`ValueError: Unknown engine: pyarrow (valid options are "c", "python", or "python-fwf")`

I have tried installing pandas1.4+, pyarrow1.0,1 to fix this problem, but it doesn't work.
Is it the version of the installation package? Could you please give the specific installation package and Python version?

**Comment by sherlie831** [comment]
After the python version was changed to 3.8, the problem above was successfully solved.
But another error occurs when import cpydvs:
```
ModuleNotFoundError: No module named 'cpydvs'
```
**Plus**: I have installed pydvs according to the instructions
```
cd lib
sudo python3 setup.py install
```
However, this command seems to install pydvs into the system Python environment, and I use the virtual environment of conda. Is there any way to solve this problem?

**Comment by aftersomemath** [comment]
Even though this is closed, I wanted to comment for any future readers.

Pandas 1.4.0 added support for the `pyarrow` engine. So versions of Pandas older than 1.4.0 will cause the `ValueError` mentioned. Upgrading the Python version may have caused the pandas version in the conda environment to be updated, thus solving the issue.

Other engines than `pyarrow` can be used, but they are much slower as noted [here](https://github.com/better-flow/pydvs/blob/e0d1a77b0a81ba8ec1524581f2f116a130c399c7/lib/pydvs.py#L159).

When using a conda environment `sudo` should not be used, so the install command should be `python3 setup.py install` (assuming the conda environment is activated).

**Comment by sherlie831** [comment]
Thanks for your reply, I solved this problem according to the following method, I hope it can give some reference:

- I found that` python3 `is the alias of my system python, so when I executed `python3 setup.py install` in the activated conda environment, which would cause pydvs to be installed in the system python environment.
- Change` python3` to `python`  Executed` python setup.py install` , but reported an error of permission denied .
- Added` alias sudo="sudo env PATH=$PATH"` to ~/.bashrc, so` sudo` can be used in conda, and then executed` sudo python setup.py install `to successfully install.


**By the way, I would like to ask after running the evimo-gen.py file, the corresponding frame_xxx.png is generated in the slice folder. What is the specific method of event aggregation? What is the meaning of the three channel values of the picture?
Looking forward to your reply，thanks！**

**Comment by aftersomemath** [comment]
Glad you got it working. For reference, the steps I used to get pydvs working in a conda environment were:

```bash
conda activate myenvironment
python3 (check top text to see this is the Anaconda python3, then close the repl)
python3 -c "import pydvs" (does not work)
python3 -c "import cpydvs" (does not work)
cd lib
python3 setup.py install
python3 -c "import pydvs" (works)
python3 -c "import cpydvs" (works)
```

The `frame_xxx.png`'s are generated by [this function](https://github.com/better-flow/pydvs/blob/master/samples/evimo-gen.py#L92) which in turn calls [this](https://github.com/better-flow/pydvs/blob/master/lib/pydvs.py) which then calls [this](https://github.com/better-flow/pydvs/blob/master/lib/pydvs.c#L7).

Roughly speaking, the image is 3 channels where the first channel is the positive event count, the second channel is the time image (average timestamp of events on a pixel), and the third channel is the negative event count. The resulting image is undistorted. Some scaling and heuristics are used throughout those functions to make the results more "visualizable".

**Comment by sherlie831** [comment]
Thank you so much for your answer. Can I understand it this way?

- In line103  `cmb[:,:,1] *= 255.0 / slice_width`，`cmb[:,:,1]`  before the operation is performed is the average timestamp of the event, then `*255/width` is scaled to the range of 0 to 255.

- In line102` cmb[:,:,0] *= 50`, `cmb[:,:,0]` before the operation is performed is the accumulation of positive events in the time window. `*50` is to increase the contrast, but if the cumulative number of events exceeds 5, it will cause it to exceed the range of 255. , how to deal with this?

**Comment by aftersomemath** [comment]
Yes that explanation is correct.

At line 102 `cmb` should still be a floating point number (cmb is defined [here](https://github.com/better-flow/pydvs/blob/master/lib/pydvs.py#L293)). So casting to a uint8 actually happens later. If you want an accurate event count you probably should not multiply by 50. If there are more than 255 events on a pixel then a larger data type will be needed when saving the result to disk. You could save the result as either a 16 bit PNG or a `.npy`. `.npy` would probably be the best option as the PNG is really for visualization.
