### ISSUE TITLE
ground truth for depth

### ISSUE THREAD

**Issue by ChenaoJIANG** [ncos/pydvs#3]
Hi, I am trying to run `evimo-gen.py `to generate time slice as input to the network. 

It will generate frame, depth, mask at the same time, but I find that the depth generated is only the part of the moving objects, 
like this
![image](https://user-images.githubusercontent.com/89578789/234603934-61983834-a07d-426f-93e5-46432346b751.png) **not the depth image including the background.** Is that normal? 

Because I need the depth like this
 ![image](https://user-images.githubusercontent.com/89578789/234604244-83edf879-0f28-4501-8d91-a81c31875713.png)

Looking forward to your reply，thanks！

**Comment by aftersomemath** [comment]
Hi,

To get background depth in EVIMO1 you will need to regenerate the dataset from the raw format. See [here](https://github.com/better-flow/evimo/issues/23#issuecomment-1265709630) for more information.

If you have more questions about regenerating the depth, please ask them on that thread.
